# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftStudy' do

  #pod 'Alamofire'
  pod 'SnapKit'

  pod 'Moya'

  # model。
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  
  pod 'QMUIKit'
  pod 'iVersion'
  
  # facebook动画
  pod 'pop'
  
  # RXSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # RXSwift Community
  pod 'RxDataSources'
  
end
